project:
  type: book
  output-dir: ../pdf

book:
  title: "Mathematical Awakening"
  subtitle: "A Deep Dive into Linear Algebra"
  chapters:
    - index.qmd
    - 1_building_intuition_for_functions_exponents_and_log.qmd
    - 2_understanding_derivative_rules_from_the_ground_up.qmd
    - 3_integral_calculus_accumulation.qmd
    - 4_multivariable_calculus_gradients.qmd
    - 5_linear_algebra_the_language_of_modern_mathematics.qmd
    - 6_advanced_linear_algebra_eigenvectors_eigenvalues_m.qmd
    - 7_probability_random_variables_making_sense_of_uncer.qmd
    - 8_from_probability_to_evidence_mastering_statistical.qmd
    - 9_the_ai_revolution_mastering_the_mathematical_found.qmd
    - 10_mathematical_mastery_in_action_from_theory_to_tril.qmd

format:
  pdf:
    toc: true
    toc-depth: 2
    number-sections: true
    top-level-division: chapter
    colorlinks: true
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
    fontsize: 11pt
    documentclass: book
    fig-pos: "H"
    code-block-bg: true
    code-block-border-left: "#ef5350"
    linestretch: 1.2
    include-before-body:
      text: |
        \RecustomVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \usepackage{fancyhdr}
        \usepackage{microtype}
        \usepackage{booktabs}
        \usepackage{amsmath}
        \usepackage{amssymb}
        \usepackage{amsthm}
        \newtheorem{theorem}{Theorem}
        \newtheorem{definition}{Definition}
        \author{Yevheniy Chuba}
        \date{2024}

execute:
  echo: true
  warning: false
  message: false

